export { copy } from './copy.js';
export { reset } from './reset.js';
export { html } from './html.js';
export { replace } from './replace.js';
export { server } from './server.js';
export { scss } from './scss.js';
export { js } from './js.js';
export { images } from './images.js';
export { otfToTtf, ttfToWoff, fontsStyle } from './fonts.js';
export { svgSprite } from './svgSprite.js';
export { zip as zipPlugin } from './zip.js';
export { ftp } from './ftp.js';
